apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gm02ksxtx-python 
  janus-idp.io/tekton: gm02ksxtx-python
  backstage.io/kubernetes-id: gm02ksxtx-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gm02ksxtx-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml