apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gm02ksxtx-python-gitops
  description: This is GitOps manifest for gm02ksxtx-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=gm02ksxtx-python
    backstage.io/kubernetes-id: gm02ksxtx-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: gm02ksxtx-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:gm02ksxtx-python
